version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    networks:
      - network-bridge
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_ROOT_HOST: "%"
    ports:
      - $DATABASE_PORT:3306
    volumes:
      - ./data:/var/lib/mysql
      - ../scripts:/docker-entrypoint-initdb.d
  app:
    container_name: simple-app-container
    depends_on:
      - mysqldb
    networks:
      - network-bridge
    build: ../
    restart: unless-stopped
    ports:
      - $PORT:3000
    environment:
      DATABASE_HOST: mysqldb
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_PORT: $DATABASE_PORT
    stdin_open: true
    tty: true

networks:
  network-bridge:
    driver: bridge

volumes: 
  db: 

